version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - app_network
    env_file:
      - ./backend/.env
    depends_on:
      - sql

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app_network
    # env_file:
    #   - ./frontend/.env

  sql:
    image: mysql:8
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - app_network
    env_file:
      - ./backend/.env
    volumes:
      - sql_data:/var/lib/mysql

networks:
  app_network:
    driver: bridge

volumes:
  sql_data:
