import room1 from "../assets/images/room1.jpg";
import room2 from "../assets/images/room2.jpg";
import room3 from "../assets/images/room3.jpg";

// sampleProperty.js

// const sampleProperty = 
//     {
//       id: 1,
//       title: "Beautiful room in a shared apartment, private balcony",
//       size: "20m²",
//       totalRent: 450,
//       cost: {
//         rent: 400,
//         extraCharges: 20,
//         warmRent: 30,
//         transferAgreement: null,
//       },
//       address: "Leipziger strasse 30A, 36039 Fulda",
//       availableFrom: "05.12.2024",
//       description: "This is a fully furnished shared apartment with modern amenities.",
//       images: [room1, room2, room3],
//       reviews: [
//         { author: "Roald Dahl", text: "Mr. Schmidt is a good person. Room is fantastic.", rating: 5 },
//         { author: "Jane Doe", text: "Very comfortable and clean.", rating: 4 },
//       ],
//       documents: ["Enrollment Certificate", "Residence Permit"],
//       contact: {
//         name: "Mr. Schmidt",
//         email: "schmidt@example.com",
//         phone: "+49 123 456 789",
//       },
//     };

const sampleProperty = [
    {
      id: 1,
      title: "Beautiful room in a shared apartment, private balcony",
      size: "20m²",
      totalRent: 450,
      cost: {
        rent: 400,
        extraCharges: 20,
        warmRent: 30,
        transferAgreement: null,
      },
      address: "Leipziger strasse 30A, 36039 Fulda",
      availableFrom: "05.12.2024",
      description: "This is a fully furnished shared apartment with modern amenities.",
      images: [room1, room2, room3],
      reviews: [
        { author: "Roald Dahl", text: "Mr. Schmidt is a good person. Room is fantastic.", rating: 5 },
        { author: "Jane Doe", text: "Very comfortable and clean.", rating: 4 },
      ],
      documents: ["Enrollment Certificate", "Residence Permit"],
      contact: {
        name: "Mr. Schmidt",
        email: "schmidt@example.com",
        phone: "+49 123 456 789",
      },
    },
    {
      id: 2,
      title: "Cozy studio apartment with city view",
      size: "30m²",
      totalRent: 500,
      cost: {
        rent: 450,
        extraCharges: 30,
        warmRent: 50,
        transferAgreement: "Available",
      },
      address: "Hauptstraße 10, 12345 Berlin",
      availableFrom: "01.01.2025",
      description: "Compact studio with a beautiful view of the city center.",
      images: [room2, room3, room1],
      reviews: [
        { author: "John Smith", text: "Great view and quiet location.", rating: 5 },
        { author: "Anna Lee", text: "Perfect for a single person, very cozy.", rating: 4 },
      ],
      documents: ["Proof of Income", "Rental Contract"],
      contact: {
        name: "Mrs. Müller",
        email: "mueller@example.com",
        phone: "+49 987 654 321",
      },
    },
    {
        id: 3,
        title: "Beautiful room in a shared apartment, private balcony",
        size: "20m²",
        totalRent: 450,
        cost: {
          rent: 400,
          extraCharges: 20,
          warmRent: 30,
          transferAgreement: null,
        },
        address: "Leipziger strasse 30A, 36039 Fulda",
        availableFrom: "05.12.2024",
        description: "This is a fully furnished shared apartment with modern amenities.",
        images: [room3, room2, room1],
        reviews: [
          { author: "Roald Dahl", text: "Mr. Schmidt is a good person. Room is fantastic.", rating: 5 },
          { author: "Jane Doe", text: "Very comfortable and clean.", rating: 4 },
        ],
        documents: ["Enrollment Certificate", "Residence Permit"],
        contact: {
          name: "Mr. Schmidt",
          email: "schmidt@example.com",
          phone: "+49 123 456 789",
        },
      },
      {
        id: 4,
        title: "Cozy studio apartment with city view",
        size: "30m²",
        totalRent: 500,
        cost: {
          rent: 450,
          extraCharges: 30,
          warmRent: 50,
          transferAgreement: "Available",
        },
        address: "Hauptstraße 10, 12345 Berlin",
        availableFrom: "01.01.2025",
        description: "Compact studio with a beautiful view of the city center.",
        images: [room1, room2, room3],
        reviews: [
          { author: "John Smith", text: "Great view and quiet location.", rating: 5 },
          { author: "Anna Lee", text: "Perfect for a single person, very cozy.", rating: 4 },
        ],
        documents: ["Proof of Income", "Rental Contract"],
        contact: {
          name: "Mrs. Müller",
          email: "mueller@example.com",
          phone: "+49 987 654 321",
        },
      },
      {
        id: 5,
        title: "Beautiful room in a shared apartment, private balcony",
        size: "20m²",
        totalRent: 450,
        cost: {
          rent: 400,
          extraCharges: 20,
          warmRent: 30,
          transferAgreement: null,
        },
        address: "Leipziger strasse 30A, 36039 Fulda",
        availableFrom: "05.12.2024",
        description: "This is a fully furnished shared apartment with modern amenities.",
        images: [room1, room2, room3],
        reviews: [
          { author: "Roald Dahl", text: "Mr. Schmidt is a good person. Room is fantastic.", rating: 5 },
          { author: "Jane Doe", text: "Very comfortable and clean.", rating: 4 },
        ],
        documents: ["Enrollment Certificate", "Residence Permit"],
        contact: {
          name: "Mr. Schmidt",
          email: "schmidt@example.com",
          phone: "+49 123 456 789",
        },
      },
      {
        id: 6,
        title: "Cozy studio apartment with city view",
        size: "30m²",
        totalRent: 500,
        cost: {
          rent: 450,
          extraCharges: 30,
          warmRent: 50,
          transferAgreement: "Available",
        },
        address: "Hauptstraße 10, 12345 Berlin",
        availableFrom: "01.01.2025",
        description: "Compact studio with a beautiful view of the city center.",
        images: [room2, room3, room1],
        reviews: [
          { author: "John Smith", text: "Great view and quiet location.", rating: 5 },
          { author: "Anna Lee", text: "Perfect for a single person, very cozy.", rating: 4 },
        ],
        documents: ["Proof of Income", "Rental Contract"],
        contact: {
          name: "Mrs. Müller",
          email: "mueller@example.com",
          phone: "+49 987 654 321",
        },
      },
      {
        id: 7,
        title: "Beautiful room in a shared apartment, private balcony",
        size: "20m²",
        totalRent: 450,
        cost: {
          rent: 400,
          extraCharges: 20,
          warmRent: 30,
          transferAgreement: null,
        },
        address: "Leipziger strasse 30A, 36039 Fulda",
        availableFrom: "05.12.2024",
        description: "This is a fully furnished shared apartment with modern amenities.",
        images: [room1, room2, room3],
        reviews: [
          { author: "Roald Dahl", text: "Mr. Schmidt is a good person. Room is fantastic.", rating: 5 },
          { author: "Jane Doe", text: "Very comfortable and clean.", rating: 4 },
        ],
        documents: ["Enrollment Certificate", "Residence Permit"],
        contact: {
          name: "Mr. Schmidt",
          email: "schmidt@example.com",
          phone: "+49 123 456 789",
        },
      },
      {
        id: 8,
        title: "Cozy studio apartment with city view",
        size: "30m²",
        totalRent: 500,
        cost: {
          rent: 450,
          extraCharges: 30,
          warmRent: 50,
          transferAgreement: "Available",
        },
        address: "Hauptstraße 10, 12345 Berlin",
        availableFrom: "01.01.2025",
        description: "Compact studio with a beautiful view of the city center.",
        images: [room2, room3, room1],
        reviews: [
          { author: "John Smith", text: "Great view and quiet location.", rating: 5 },
          { author: "Anna Lee", text: "Perfect for a single person, very cozy.", rating: 4 },
        ],
        documents: ["Proof of Income", "Rental Contract"],
        contact: {
          name: "Mrs. Müller",
          email: "mueller@example.com",
          phone: "+49 987 654 321",
        },
      },
      {
        id: 9,
        title: "Beautiful room in a shared apartment, private balcony",
        size: "20m²",
        totalRent: 450,
        cost: {
          rent: 400,
          extraCharges: 20,
          warmRent: 30,
          transferAgreement: null,
        },
        address: "Leipziger strasse 30A, 36039 Fulda",
        availableFrom: "05.12.2024",
        description: "This is a fully furnished shared apartment with modern amenities.",
        images: [room1, room2, room3],
        reviews: [
          { author: "Roald Dahl", text: "Mr. Schmidt is a good person. Room is fantastic.", rating: 5 },
          { author: "Jane Doe", text: "Very comfortable and clean.", rating: 4 },
        ],
        documents: ["Enrollment Certificate", "Residence Permit"],
        contact: {
          name: "Mr. Schmidt",
          email: "schmidt@example.com",
          phone: "+49 123 456 789",
        },
      },
      {
        id: 10,
        title: "Cozy studio apartment with city view",
        size: "30m²",
        totalRent: 500,
        cost: {
          rent: 450,
          extraCharges: 30,
          warmRent: 50,
          transferAgreement: "Available",
        },
        address: "Hauptstraße 10, 12345 Berlin",
        availableFrom: "01.01.2025",
        description: "Compact studio with a beautiful view of the city center.",
        images: [room2, room3, room1],
        reviews: [
          { author: "John Smith", text: "Great view and quiet location.", rating: 5 },
          { author: "Anna Lee", text: "Perfect for a single person, very cozy.", rating: 4 },
        ],
        documents: ["Proof of Income", "Rental Contract"],
        contact: {
          name: "Mrs. Müller",
          email: "mueller@example.com",
          phone: "+49 987 654 321",
        },
      },
      {
        id: 11,
        title: "Beautiful room in a shared apartment, private balcony",
        size: "20m²",
        totalRent: 450,
        cost: {
          rent: 400,
          extraCharges: 20,
          warmRent: 30,
          transferAgreement: null,
        },
        address: "Leipziger strasse 30A, 36039 Fulda",
        availableFrom: "05.12.2024",
        description: "This is a fully furnished shared apartment with modern amenities.",
        images: [room1, room2, room3],
        reviews: [
          { author: "Roald Dahl", text: "Mr. Schmidt is a good person. Room is fantastic.", rating: 5 },
          { author: "Jane Doe", text: "Very comfortable and clean.", rating: 4 },
        ],
        documents: ["Enrollment Certificate", "Residence Permit"],
        contact: {
          name: "Mr. Schmidt",
          email: "schmidt@example.com",
          phone: "+49 123 456 789",
        },
      },
      {
        id: 13,
        title: "Cozy studio apartment with city view",
        size: "30m²",
        totalRent: 500,
        cost: {
          rent: 450,
          extraCharges: 30,
          warmRent: 50,
          transferAgreement: "Available",
        },
        address: "Hauptstraße 10, 12345 Berlin",
        availableFrom: "01.01.2025",
        description: "Compact studio with a beautiful view of the city center.",
        images: [room2, room3, room1],
        reviews: [
          { author: "John Smith", text: "Great view and quiet location.", rating: 5 },
          { author: "Anna Lee", text: "Perfect for a single person, very cozy.", rating: 4 },
        ],
        documents: ["Proof of Income", "Rental Contract"],
        contact: {
          name: "Mrs. Müller",
          email: "mueller@example.com",
          phone: "+49 987 654 321",
        },
      },

      {
        id: 12,
        title: "Cozy studio apartment with city view",
        size: "30m²",
        totalRent: 500,
        cost: {
          rent: 450,
          extraCharges: 30,
          warmRent: 50,
          transferAgreement: "Available",
        },
        address: "Hauptstraße 10, 12345 Berlin",
        availableFrom: "01.01.2025",
        description: "Compact studio with a beautiful view of the city center.",
        images: [room2, room3, room1],
        reviews: [
          { author: "John Smith", text: "Great view and quiet location.", rating: 5 },
          { author: "Anna Lee", text: "Perfect for a single person, very cozy.", rating: 4 },
        ],
        documents: ["Proof of Income", "Rental Contract"],
        contact: {
          name: "Mrs. Müller",
          email: "mueller@example.com",
          phone: "+49 987 654 321",
        },
      },

  ];
  
  export { sampleProperty };
  