name: Deploy to EC2

on:
  push:
    branches: ["main"]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - run: mkdir -p ~/.ssh/
      - run: echo "${{ secrets.EC2_PRIV_KEY}}" > ~/.ssh/id_rsa
      - run: chmod 600 ~/.ssh/id_rsa
      - run: ssh -t -o StrictHostKeyChecking=no -p ${{ secrets.EC2_HOST_PORT }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST_IP }} "/home/ubuntu/deploy.sh"
